add rallly
onedr0p/containers pull request #67
Opened 2022-09-06 22:02 UTC by luclu

https://github.com/lukevella/rallly

2022-09-07 20:26 UTC, onedr0p requested changes

2022-09-07 20:26 UTC, onedr0p commented on apps/rallly/Dockerfile
> +    SMTP_PWD=your-smtp-password
Please only include bare minimum required env vars needed for the application to run

2022-09-07 20:26 UTC, onedr0p commented on apps/rallly/README.md
> +| SMTP_PWD             | `your-smtp-password`                             |
This section can be delete as it is not a custom configuration we are scaffolding with `envsubt`. I expect people to be able to do research and look up env vars if they are properly supported by the application itself.

2022-09-07 20:26 UTC, onedr0p commented on apps/rallly/README.md
> +In your kubernetes manifest override CMD with `sh -c "yarn prisma migrate deploy --schema prisma/schema.prisma && yarn start"`.
```suggestion
## Nuances

In your kubernetes manifest override CMD with `sh -c "yarn prisma migrate deploy --schema prisma/schema.prisma && yarn start"`.
```

2022-09-07 20:26 UTC, onedr0p commented on apps/rallly/metadata.json
> +    }
Any reason why you have 2 channels here? In most cases we should just be building the most stable version of the app.

2022-09-07 20:51 UTC, onedr0p commented on apps/rallly/Dockerfile
> +    SMTP_PWD=your-smtp-password
Are the others required for the app to start?

2022-09-07 20:52 UTC, onedr0p commented on apps/rallly/metadata.json
> +      "name": "production",
```suggestion
      "name": "stable",
```

2022-09-07 21:54 UTC, onedr0p commented on apps/rallly/metadata.json
> +      "name": "production",
Not necessarily, it can just be stable when there's one channel

2022-09-14 22:13 UTC, onedr0p commented on apps/rallly/metadata.json
> +      "name": "production",
Sorry I haven't forgot about this, just been busy.

2022-09-15 19:47 UTC, onedr0p commented on apps/rallly/metadata.json
> +      "name": "production",
Is there any confirmation on the production branch being updated, should we just use main instead?

2022-09-17 04:54 UTC, samip5 commented on apps/rallly/metadata.json
> +      "name": "production",
> Is there any confirmation on the production branch being updated, should we just use main instead?

There has been "The main branch is considered production and is what's available on rallly.co."

2022-09-17 04:55 UTC, samip5 commented
Please remember arm64 platform too. :)

2022-09-17 10:26 UTC, onedr0p commented on apps/rallly/metadata.json
> +      "name": "production",
We can just hardcode "stable" in the metadata.json and main in the latest and Dockerfile scripts. I don't foresee long-lived branches that will need to be built and ran.

2022-09-19 23:42 UTC, onedr0p approved these changes

2022-09-19 23:42 UTC, merged